import { Component, NgModule, OnInit } from '@angular/core';
import { Note } from '../note';
import { NoteService } from '../note.service';
import { MessageService } from '../message.service';
import { Game } from '../game';
import { GameService } from '../game.service';
@Component({
  selector: 'app-save-point-note',
  templateUrl: './save-point-note.component.html',
  styleUrls: ['./save-point-note.component.css'],
})


export class SavePointNoteComponent implements OnInit {

  notes: Note[] = [];
  games: Game[] = [];
  constructor(private noteService: NoteService, private messageService: MessageService, private gameService: GameService) { }

  ngOnInit(): void {
    this.getNotes();
    this.getGames();
  }

  selectedNote?: Note;
  onSelect(note: Note): void {
    this.selectedNote = note;
    this.messageService.add(`NotesComponent: Selected note id=${note.savePointNoteId}`)
  }

  getGames(): void {
    this.gameService.getGames()
      .subscribe(games => this.games = games);
  }
  getNotes(): void {
    this.noteService.getNotes()
      .subscribe(notes => this.notes = notes);
  }

  addNote(note: string, savePointGameId: string) {
    // convert the game id to a number
    const gameId = Number(savePointGameId);

    // create a new note object
    const newNote: Note = {
      savePointNoteId: 0, // replace 0 with the appropriate value
      // FYI, the note date will be automatically generated by the API
      note,
      savePointGameId: gameId,
      noteDate: new Date().toISOString(),
    };

    console.log(newNote);

    // push the new note to the API
    this.noteService.addNote(newNote).subscribe(note => this.notes.push(note));
    console.log("Note Added!");
  }

  save() {

    console.log("Note Saved!");
  }

  delete() {
    console.log("Note Deleted!");
  }

}
